
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
/**
 * Return the cached host list (populated at startup / on reload, tech-gui.md §4.2).
 */
async listHosts() : Promise<Result<HostDto[], CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_hosts") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Reload hosts from the shared config, refresh the cache, restart the pollers,
 * bring running tunnels in line with the edit, and broadcast the new list via
 * `hosts-loaded` followed by every live tunnel's status (tech-gui.md §4.2). Also
 * the startup entry point: the frontend calls it once its event bridge is up,
 * which is when tunnels autostart.
 */
async reloadHosts() : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("reload_hosts") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Add or edit a host and persist to `hosts.toml` (tech-gui.md §4.2, Stage 4.1).
 * Upserts by name. Editing an SSH-config import adopts it: the saved copy is a manual
 * entry that `merge_hosts` then prefers over the parsed one, so `~/.ssh/config` itself
 * is still never written. The frontend calls `reload_hosts` afterwards to refresh the
 * merged cache + restart the pollers. Secrets stay backend-side (§3.4): the payload's
 * password/identity never left the backend.
 */
async saveHost(input: HostInputDto) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_host", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Delete a manual host by name and persist (tech-gui.md §4.2, Stage 4.1). Only manual
 * entries live in `hosts.toml`, so an SSH-config name — or a missing one — is a no-op
 * success: the desired end state (absent) already holds.
 */
async deleteHost(name: string) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_host", { name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * List saved snippets from the shared `snippets.toml` (tech-gui.md §4.2).
 */
async listSnippets() : Promise<Result<SnippetDto[], CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_snippets") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Upsert a snippet by name and persist the whole list (tech-gui.md §4.2). A new
 * name appends; an existing name is replaced in place (an in-place edit). A rename
 * is a frontend delete-old + save-new, since the contract keys snippets on `name`.
 */
async saveSnippet(snippet: SnippetDto) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_snippet", { snippet }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Delete the snippet named `name` and persist (tech-gui.md §4.2). A missing name is
 * a no-op success — the desired end state (absent) already holds.
 */
async deleteSnippet(name: string) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_snippet", { name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Execute a snippet on one or more hosts (tech-gui.md §4.2). Substitutes the
 * provided values into declared placeholders, then fires one task per host that
 * runs the command over a fresh SSH session and emits a `snippet-result` (§4.3).
 * Fire-and-forget: results arrive as events, mirroring the core's own model.
 */
async executeSnippet(snippetName: string, hostNames: string[], params: Partial<{ [key in string]: string }>) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("execute_snippet", { snippetName, hostNames, params }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Open a terminal for `host_name`, streaming raw output into `on_output`. Returns
 * the public session id used by the write/resize/close commands (tech-gui.md §4.2).
 */
async terminalOpen(hostName: string, cols: number, rows: number, onOutput: TAURI_CHANNEL<TerminalBytes>) : Promise<Result<number, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("terminal_open", { hostName, cols, rows, onOutput }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Send keystrokes / pasted bytes to a terminal (tech-gui.md §4.2). Input is
 * low-volume, so the ordinary `number[]` path is fine here (only output is raw).
 */
async terminalWrite(sessionId: number, data: number[]) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("terminal_write", { sessionId, data }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Reflow a terminal to `cols` x `rows` (tech-gui.md §4.2).
 */
async terminalResize(sessionId: number, cols: number, rows: number) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("terminal_resize", { sessionId, cols, rows }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Close a terminal and its connection (tech-gui.md §4.2). The frontend has already
 * dropped the tab, so the resulting `PtyExited` emits no `terminal-exited` (§3.4).
 */
async terminalClose(sessionId: number) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("terminal_close", { sessionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Paste into the focused terminal the way the webview's own Ctrl+Shift+V does.
 * WebKitGTK binds that chord by its key symbol, so under a non-Latin layout it never
 * fires and the frontend asks here instead. The other webviews bind it by the
 * physical key and never need this.
 */
async terminalPaste() : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("terminal_paste") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Open an SFTP session for `host_name` (tech-gui.md §4.2). Awaits the core connect,
 * registers the manager under a fresh public id, and spawns the per-session
 * forwarder; the `sftp-connected` ack then arrives stamped with that id (§3.4).
 */
async sftpOpen(hostName: string) : Promise<Result<number, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("sftp_open", { hostName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * List a remote directory (tech-gui.md §4.2); the result arrives as `sftp-dir-listed`.
 */
async sftpList(sessionId: number, path: string) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("sftp_list", { sessionId, path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Upload a local file to a remote path (tech-gui.md §4.2). Allocates a transfer id
 * owned by this session so `transfer-progress` routes back to the tab (§3.4).
 */
async sftpUpload(sessionId: number, local: string, remote: string) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("sftp_upload", { sessionId, local, remote }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Download a remote file to a local path (tech-gui.md §4.2). See `sftp_upload` for
 * the transfer-id routing; the core guards the local destination against `..` (§3.2).
 */
async sftpDownload(sessionId: number, local: string, remote: string) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("sftp_download", { sessionId, local, remote }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Create a remote directory (tech-gui.md §4.2); completion arrives as `sftp-op-done`.
 */
async sftpMkdir(sessionId: number, path: string) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("sftp_mkdir", { sessionId, path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Rename / move a remote path (tech-gui.md §4.2).
 */
async sftpRename(sessionId: number, from: string, to: string) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("sftp_rename", { sessionId, from, to }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Delete a remote file (falls back to an empty directory in the core) (tech-gui.md §4.2).
 */
async sftpDelete(sessionId: number, path: string) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("sftp_delete", { sessionId, path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Read a remote file's preview bytes (tech-gui.md §4.2); arrives as `file-preview`.
 */
async sftpPreview(sessionId: number, path: string) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("sftp_preview", { sessionId, path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Close an SFTP session and its connection (tech-gui.md §4.2).
 */
async sftpClose(sessionId: number) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("sftp_close", { sessionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * List a local directory (tech-gui.md §4.2). Returns directly off the async worker;
 * the GUI never emits `LocalDirListed` (§4.3). The core prepends a `..` entry and
 * sorts dirs-first.
 */
async listLocalDir(path: string) : Promise<Result<FileEntryDto[], CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_local_dir", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * The roots the local pane can switch to: every drive letter on Windows, `/`
 * elsewhere (tech-gui.md §4.2).
 */
async listLocalRoots() : Promise<string[]> {
    return await TAURI_INVOKE("list_local_roots");
},
/**
 * Read up to 4 KiB of a local file as UTF-8 for preview (tech-gui.md §4.2).
 */
async previewLocalFile(path: string) : Promise<Result<string, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("preview_local_file", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Start auto key-setup for `host_name` (tech-gui.md §4.2). Fire-and-forget: the flow
 * runs on a background task and reports via `key-setup-*` events, mirroring the core's
 * own model. Resolving the full host record (secrets included) stays backend-side
 * (§3.4). One run at a time: an unknown host or a run already in flight is the
 * synchronous error, so two runs never race a `hosts.toml` write.
 */
async startKeySetup(hostName: string) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_key_setup", { hostName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Start `hostName`'s tunnel, or restart it if one is running. Async because the
 * tunnel is spawned onto the Tauri runtime.
 */
async tunnelStart(hostName: string) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("tunnel_start", { hostName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Stop `hostName`'s tunnel. A no-op when none runs.
 */
async tunnelStop(hostName: string) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("tunnel_stop", { hostName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Trigger an immediate metric poll of every host (tech-gui.md §4.2). Used by the
 * settings-driven refresh cadence (§4.3); a no-op before the pollers start.
 */
async refreshMetrics() : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("refresh_metrics") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Decrypt `key_path` with `passphrase` and remember it for this process. Only a
 * key the core reported in `key-passphrase-required` is accepted; connections
 * waiting on it retry at once.
 */
async unlockIdentity(keyPath: string, passphrase: string) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("unlock_identity", { keyPath, passphrase }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Answer the `password-required` prompt `request_id`: a password to try, or
 * `null` to cancel that login. The connection checks it with the server and
 * asks again if it is refused.
 */
async answerPassword(requestId: number, password: string | null) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("answer_password", { requestId, password }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Minimize and close to the tray, or not. Resolves to what this desktop allows —
 * a tray at all, and minimizing into it; what it does not, the window keeps doing
 * as before.
 */
async setTrayBehavior(minimizeToTray: boolean, closeToTray: boolean) : Promise<Result<TraySupportDto, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_tray_behavior", { minimizeToTray, closeToTray }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Query GitHub for a newer release (tech-gui.md §4.2). `None` means up to date — the
 * core swallows network/parse errors so a failed check never disrupts.
 */
async checkUpdate() : Promise<Result<UpdateInfoDto | null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("check_update") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Download and install the latest desktop bundle via `tauri-plugin-updater` (tech-gui.md
 * §4.3/§3.7). Until Stage 5 configures the updater endpoints + signing key the plugin
 * has nothing to point at, so this reports "not available yet" rather than touching the
 * running binary.
 */
async installUpdate() : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("install_update") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Read the update-checker preferences from the shared config (tech-gui.md §4.3).
 */
async loadUpdateConfig() : Promise<Result<UpdateConfigDto, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("load_update_config") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Persist the update-checker preferences to the shared config's `[update]` section
 * (tech-gui.md §4.3). Writes off the async worker — parse + atomic write are blocking.
 */
async saveUpdateConfig(config: UpdateConfigDto) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_update_config", { config }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/


export const events = __makeEvents__<{
error: Error,
filePreview: FilePreview,
hostStatusChanged: HostStatusChanged,
hostsLoaded: HostsLoaded,
keyPassphraseRequired: KeyPassphraseRequired,
keySetupComplete: KeySetupComplete,
keySetupFailed: KeySetupFailed,
keySetupProgress: KeySetupProgress,
keySetupRollback: KeySetupRollback,
metricsUpdated: MetricsUpdated,
passwordRequired: PasswordRequired,
servicesDetected: ServicesDetected,
servicesFailed: ServicesFailed,
sftpConnected: SftpConnected,
sftpDirListed: SftpDirListed,
sftpDisconnected: SftpDisconnected,
sftpOpDone: SftpOpDone,
snippetResult: SnippetResult,
terminalExited: TerminalExited,
transferProgress: TransferProgress,
tunnelStatusChanged: TunnelStatusChanged,
updateAvailable: UpdateAvailable
}>({
error: "error",
filePreview: "file-preview",
hostStatusChanged: "host-status-changed",
hostsLoaded: "hosts-loaded",
keyPassphraseRequired: "key-passphrase-required",
keySetupComplete: "key-setup-complete",
keySetupFailed: "key-setup-failed",
keySetupProgress: "key-setup-progress",
keySetupRollback: "key-setup-rollback",
metricsUpdated: "metrics-updated",
passwordRequired: "password-required",
servicesDetected: "services-detected",
servicesFailed: "services-failed",
sftpConnected: "sftp-connected",
sftpDirListed: "sftp-dir-listed",
sftpDisconnected: "sftp-disconnected",
sftpOpDone: "sftp-op-done",
snippetResult: "snippet-result",
terminalExited: "terminal-exited",
transferProgress: "transfer-progress",
tunnelStatusChanged: "tunnel-status-changed",
updateAvailable: "update-available"
})

/** user-defined constants **/



/** user-defined types **/

export type CommandError = { message: string }
/**
 * Live connection state for a host (tech-gui.md §4.1). Internally tagged so the
 * frontend consumes a discriminated union keyed on `kind`.
 */
export type ConnectionStatusDto = { kind: "unknown" } | { kind: "connecting" } | { kind: "connected" } | { kind: "failed"; message: string }
/**
 * A background error surfaced to the user.
 */
export type Error = { message: string }
/**
 * A file or directory in an SFTP panel listing (tech-gui.md §4.1). Maps from the
 * core `FileEntry`; `path` is the absolute path the frontend marks entries by.
 */
export type FileEntryDto = { name: string; path: string; size: number; isDir: boolean }
/**
 * Preview bytes for a remote file (tech-gui.md §4.3). Stamped with `sessionId`; the
 * core `FilePreviewReady` carries only the path + content (§3.4).
 */
export type FilePreview = { sessionId: number; path: string; content: string }
/**
 * A host as the frontend sees it — password and private-key material omitted
 * (tech-gui.md §3.4). `hasKey` reports whether an identity file is configured;
 * the key path itself never crosses the boundary.
 */
export type HostDto = { name: string; hostname: string; user: string; port: number; tags: string[]; notes?: string | null; source: HostSourceDto; hasKey: boolean; passwordAuthDisabled?: boolean | null; monitoring: MonitorModeDto; monitorPort?: number | null; localForwards: LocalForwardDto[]; tunnelAutostart: boolean; forwardAgent: boolean }
/**
 * Inbound host form payload for `save_host` (tech-gui.md §4.1, Stage 4.1). Always
 * builds a **manual** `Host`: editing an SSH-config import saves a copy that shadows
 * it, and `~/.ssh/config` itself is never written.
 * `password`/`identityFile` arrive here (the create/edit form owns them) but never
 * travel back out: the outbound `HostDto` omits both (§3.4). Inbound only, so it
 * derives `Deserialize` (not `Serialize`).
 */
export type HostInputDto = { name: string; hostname: string; user: string; port: number; identityFile?: string | null; password?: string | null; proxyJump?: string | null; tags: string[]; notes?: string | null; monitoring?: MonitorModeDto | null; monitorPort?: number | null; localForwards: LocalForwardDto[]; tunnelAutostart: boolean; forwardAgent: boolean }
/**
 * Host origin, mirrors `omnyssh_core::ssh::client::HostSource`.
 */
export type HostSourceDto = "sshConfig" | "manual"
/**
 * A host's connection status changed (tech-gui.md §4.3).
 */
export type HostStatusChanged = { hostName: string; status: ConnectionStatusDto }
/**
 * Full host list broadcast. Emitted by `reload_hosts` after refreshing the
 * cache; the bridge does not map `HostsLoaded` (tech-gui.md §3.4).
 */
export type HostsLoaded = HostDto[]
/**
 * A private key is encrypted and no passphrase is cached yet. Frontends prompt
 * once per key path; the passphrase never crosses back out of the backend.
 */
export type KeyPassphraseRequired = { hostName: string; keyPath: string }
/**
 * Key setup finished successfully — key auth is configured (tech-gui.md §4.3).
 * `keyPath` is the generated private-key path (a path, never key material, §3.4).
 */
export type KeySetupComplete = { hostName: string; keyPath: string }
/**
 * Key setup failed before touching the server's auth config (tech-gui.md §4.3).
 * Password authentication is never disabled unless a key was verified first.
 */
export type KeySetupFailed = { hostName: string; error: string }
/**
 * A progress step of an auto key-setup run (tech-gui.md §4.3). Mapped by the shared
 * engine bridge from `CoreEvent::KeySetupProgress`; the host name identifies the run.
 */
export type KeySetupProgress = { hostName: string; step: KeySetupStepDto }
/**
 * Key setup rolled the server's sshd config back after a late failure (tech-gui.md
 * §4.3). `result` is the human-readable rollback outcome.
 */
export type KeySetupRollback = { hostName: string; result: string }
/**
 * One step of the auto key-setup flow, for the progress view (tech-gui.md §4.2/§4.3).
 * `index` is 1-based (`1..=total`); `description` is the core's human-readable label.
 * Maps from the core `KeySetupStep`.
 */
export type KeySetupStepDto = { index: number; total: number; description: string }
/**
 * One `ssh -L` rule (tech-gui.md §4.1): listen on `bindAddress:bindPort` here and
 * reach `remoteHost:remotePort` as the host resolves it. No `bindAddress` means the
 * loopback, as with ssh.
 */
export type LocalForwardDto = { bindAddress?: string | null; bindPort: number; remoteHost: string; remotePort: number }
/**
 * A metrics snapshot for a host (tech-gui.md §4.1). The core's `Instant` is
 * flattened to `ageSeconds` (seconds since the sample) so it can serialise.
 */
export type MetricsDto = { cpuPercent?: number | null; ramPercent?: number | null; diskPercent?: number | null; uptime?: string | null; loadAvg?: string | null; osInfo?: string | null; topProcesses: ProcessDto[]; ageSeconds: number }
/**
 * A fresh metrics sample for a host (tech-gui.md §4.3).
 */
export type MetricsUpdated = { hostName: string; metrics: MetricsDto }
/**
 * How a host is watched, mirrors `omnyssh_core::ssh::client::MonitorMode`
 * (tech-gui.md §4.1). `tcpPort` means reachability only — no login, no metrics.
 */
export type MonitorModeDto = "ssh" | "tcpPort"
/**
 * A connection waits for the login password of `login` (`user@host`). Answered
 * with `answer_password`; the password only ever crosses inbound. `retry` says
 * the previous one was refused; `newHostKey` is the fingerprint of a host key
 * first seen on this connection, to check before typing.
 */
export type PasswordRequired = { requestId: number; hostName: string; login: string; retry: boolean; newHostKey: string | null }
/**
 * A single process in the "top processes" panel (tech-gui.md §4.1).
 */
export type ProcessDto = { name: string; cpuPercent: number; memPercent: number }
/**
 * A service detected on a host with its quick-scan metrics (tech-gui.md §4.1).
 */
export type ServiceDto = { kind: ServiceKindDto; metrics: ServiceMetricDto[] }
/**
 * A service kind detected on a host, mirrors `omnyssh_core::event::ServiceKind`.
 * Wire names are lowercase (`docker`, `nginx`, `postgresql`, `redis`, `nodejs`);
 * if the core adds a kind, extend this enum so it is never silently dropped
 * (tech-gui.md §4.1).
 */
export type ServiceKindDto = "docker" | "nginx" | "postgresql" | "redis" | "nodejs"
/**
 * One quick-scan metric for a detected service (tech-gui.md §4.1). `MetricValue`
 * is integer-only today; widen this if the core adds a non-integral variant.
 */
export type ServiceMetricDto = { name: string; value: number }
/**
 * Services detected on a host by the discovery quick-scan (tech-gui.md §4.3).
 */
export type ServicesDetected = { hostName: string; services: ServiceDto[] }
/**
 * Discovery failed for a host (tech-gui.md §4.3).
 */
export type ServicesFailed = { hostName: string; message: string }
/**
 * An SFTP session connected (tech-gui.md §4.3). The per-session forwarder stamps
 * `sessionId` from the channel's owner — the core `SftpConnected` carries only the
 * host name (§3.4).
 */
export type SftpConnected = { sessionId: number; hostName: string }
/**
 * A remote directory listing completed for one SFTP tab (tech-gui.md §4.3). Stamped
 * with `sessionId`; the core `FileDirListed` carries only the path (§3.4).
 */
export type SftpDirListed = { sessionId: number; path: string; entries: FileEntryDto[] }
/**
 * An SFTP operation reported a failure (tech-gui.md §4.3). The core emits this on a
 * listing error with a human reason; it does not by itself tear the session down.
 */
export type SftpDisconnected = { sessionId: number; reason: string }
/**
 * A mutating SFTP op (upload/download/mkdir/rename/delete) finished (tech-gui.md
 * §4.3). The core's `Result<(), String>` is flattened to `ok` + an optional `error`.
 */
export type SftpOpDone = { sessionId: number; ok: boolean; error?: string | null }
/**
 * A saved command snippet as the frontend sees it (tech-gui.md §4.1). Crosses the
 * boundary both ways — outbound for `list_snippets`, inbound for `save_snippet` —
 * so it derives `Deserialize` too. Optional fields are omitted when absent, matching
 * the sparse `snippets.toml` the TUI writes.
 */
export type SnippetDto = { name: string; command: string; scope: SnippetScopeDto; host?: string | null; tags?: string[] | null; params?: string[] | null }
/**
 * Result of running a snippet on one host (tech-gui.md §4.3). Emitted directly by
 * `execute_snippet` per host (one-shot `SshSession::run_command`), not via the
 * shared bridge — the same "the command owns the result" pattern the SFTP
 * per-session forwarder uses (§3.4). The core's `Result<String, String>` is
 * flattened to `ok` + `output` (stdout on success, the error message on failure).
 */
export type SnippetResult = { hostName: string; snippetName: string; ok: boolean; output: string }
/**
 * Snippet scope, mirrors `omnyssh_core::config::snippets::SnippetScope`. Wire
 * names are lowercase (`global`, `host`).
 */
export type SnippetScopeDto = "global" | "host"
/**
 * Raw PTY output bytes for a terminal session's per-session `Channel` (tech-gui.md
 * §3.3/§3.6). Deliberately **not** `Serialize`: that dodges the blanket
 * `Serialize -> IpcResponse` mapping (which would JSON-encode to a slow `number[]`),
 * so the bytes ride the channel as a raw `ArrayBuffer` that xterm writes directly.
 * Only ever sent, never received — the sole non-DTO on the boundary.
 */
export type TerminalBytes = number[]
/**
 * A terminal session's remote shell exited or its connection dropped (tech-gui.md
 * §4.3). Carries the **public** registry id (the bridge maps the core's inner PTY
 * id, §3.4); the frontend tears the tab down. User-initiated closes never emit this.
 */
export type TerminalExited = { sessionId: number }
/**
 * Live transfer progress (tech-gui.md §4.3). The payload is `TransferProgressDto`,
 * routed to its owning session via `transfer_owner` (§3.4/§4.1).
 */
export type TransferProgress = TransferProgressDto
/**
 * Live progress for one SFTP upload/download (tech-gui.md §4.1). The GUI allocates
 * `transferId` when it issues the transfer and resolves its owning `sessionId` via
 * `transfer_owner` (§3.4); `done`/`total` are byte counts (`total` is `0` when the
 * remote size could not be determined).
 */
export type TransferProgressDto = { sessionId: number; transferId: number; done: number; total: number }
/**
 * What this desktop allows the tray (tech-gui.md §4.2 `set_tray_behavior`): an icon
 * at all, and hiding a minimized window into it.
 */
export type TraySupportDto = { available: boolean; minimize: boolean }
/**
 * A host's port-forwarding tunnel changed state (tech-gui.md §4.3).
 */
export type TunnelStatusChanged = { hostName: string; status: TunnelStatusDto }
/**
 * Where a host's tunnel stands (tech-gui.md §4.1). Internally tagged on `kind`,
 * like `ConnectionStatusDto`.
 */
export type TunnelStatusDto = { kind: "connecting" } | { kind: "up" } | { kind: "retrying"; message: string } | { kind: "failed"; message: string } | { kind: "stopped" }
/**
 * A newer release was found by the startup check (tech-gui.md §4.3). Mapped by the
 * shared engine bridge from `CoreEvent::UpdateAvailable`; drives the update banner.
 */
export type UpdateAvailable = { info: UpdateInfoDto }
/**
 * Update-checker preferences, mirrors core `UpdateConfig` (tech-gui.md §4.3). Crosses
 * both ways: outbound for the settings screen, inbound for `save_update_config`.
 */
export type UpdateConfigDto = { checkOnStartup: boolean; skipVersion: string }
/**
 * A newer release the app can offer (tech-gui.md §4.1). `version` is the latest
 * version (no leading `v`); `url` is the release page; `canSelfUpdate` mirrors the
 * core's self-update eligibility. The core `UpdateInfo` has no release-notes field, so
 * none is invented (§4.1).
 */
export type UpdateInfoDto = { version: string; url: string; tag: string; canSelfUpdate: boolean }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
